# Generated by Django 3.1 on 2020-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='sol',
            field=models.IntegerField(default=0),
        ),
    ]
